tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "python@3.9"
brew "cmake"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "mas"
brew "neovim"
brew "node"
brew "ripgrep"
brew "tmux"
brew "youtube-dl"
cask "1password"
cask "alfred"
cask "anki"
cask "firefox"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-inconsolata"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "numi"
cask "obs"
cask "obsidian"
cask "qmk-toolbox"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
mas "Amphetamine", id: 937984704
mas "Aruba VIA", id: 1439900554
mas "DaVinci Resolve", id: 571213070
mas "Hidden Bar", id: 1452453066
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
