tap "buo/cask-upgrade"
tap "caarlos0/tap"
tap "charmbracelet/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "xz"
brew "jpeg-xl"
brew "aom"
brew "bat"
brew "boost"
brew "glib"
brew "readline"
brew "sqlite"
brew "python@3.9"
brew "cmake"
brew "fd"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libarchive"
brew "libass"
brew "tesseract"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "hugo"
brew "mas"
brew "neovim"
brew "node"
brew "openssl@3"
brew "openvdb"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "syncthing"
brew "tmux"
brew "tree"
brew "ttyd", args: ["HEAD"]
brew "zlib"
brew "caarlos0/tap/timer"
brew "charmbracelet/tap/vhs"
brew "heroku/brew/heroku"
cask "1password"
cask "alfred"
cask "alt-tab"
cask "anki"
cask "bluesnooze"
cask "brave-browser"
cask "clipy"
cask "discord"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-inconsolata"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-ubuntu-mono"
cask "google-chrome"
cask "iterm2"
cask "kitty"
cask "linear-linear"
cask "notion"
cask "numi"
cask "obs"
cask "obsidian"
cask "qmk-toolbox"
cask "runelite"
cask "skype"
cask "spotify"
cask "todoist"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "Amphetamine", id: 937984704
mas "DaVinci Resolve", id: 571213070
mas "Day One", id: 1055511498
mas "Hidden Bar", id: 1452453066
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Xcode", id: 497799835
