tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "aom"
brew "bat"
brew "glib"
brew "python@3.9"
brew "cmake"
brew "fd"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "python@3.10"
brew "libass"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "hugo"
brew "mas"
brew "neovim"
brew "node"
brew "openvdb"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "youtube-dl"
cask "1password"
cask "alfred"
cask "anki"
cask "discord"
cask "firefox"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-inconsolata"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "numi"
cask "obs"
cask "obsidian"
cask "qmk-toolbox"
cask "skype"
cask "spotify"
cask "todoist"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "Amphetamine", id: 937984704
mas "DaVinci Resolve", id: 571213070
mas "Hidden Bar", id: 1452453066
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Xcode", id: 497799835
