#!/usr/bin/env bash

create_symlink() {
    local target_file=$1
    local link_file=$2

    if [ -L "$link_file" ]; then
        unlink "$link_file"
    fi
    ln -s "$target_file" "$link_file"
    echo "$link_file -> $target_file"
}

DOTFILES_DIR="$HOME/.dotfiles"

setup_personal_symlinks() {
    echo "Setting up personal symlinks"
    echo "==========================================="
    create_symlink "$DOTFILES_DIR/zshrc/.zshrc" "$HOME/.zshrc"
    create_symlink "$DOTFILES_DIR/Brewfile" "$HOME/Brewfile"
    create_symlink "$DOTFILES_DIR/bin" "$HOME/bin"
}

setup_work_symlinks() {
    echo "Setting up work symlinks"
    echo "==========================================="
    create_symlink "$DOTFILES_DIR/private/.zshrc" "$HOME/.zshrc"
    create_symlink "$DOTFILES_DIR/private/Brewfile" "$HOME/Brewfile"
    # create_symlink "$DOTFILES_DIR/bin" "$HOME/bin"
}

setup_common_symlinks() {
    echo "Setting up common symlinks"
    echo "==========================================="
    create_symlink "$DOTFILES_DIR/tmux/.tmux.conf" "$HOME/.tmux.conf"
    create_symlink "$DOTFILES_DIR/nvim" "$HOME/.config/nvim"
    create_symlink "$DOTFILES_DIR/kitty" "$HOME/.config/kitty"
    create_symlink "$DOTFILES_DIR/lazygit" "$HOME/.config/lazygit"
    create_symlink "$DOTFILES_DIR/zshrc/aliases.zsh" "$HOME/.oh-my-zsh/custom/aliases.zsh"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        create_symlink "$DOTFILES_DIR/macos/DefaultKeyBinding.dict" "$HOME/Library/KeyBindings/DefaultKeyBinding.dict"
    fi
}

# Git configurations
# Not sure where else to put these, so they're here
git config --global core.editor nvim
git config --global init.defaultBranch main
git config --global include.path "$HOME/.dotfiles/git/aliases"
git config --global core.excludesFile "$HOME/.dotfiles/git/gitignore"
git config --global merge.commit no

if [ "$1" == "home" ]; then
    setup_personal_symlinks
    echo ""
    setup_common_symlinks
elif [ "$1" == "work" ]; then
    setup_work_symlinks
    echo ""
    setup_common_symlinks
else
    echo "Usage: $0 [home|work]"
    exit 1
fi

