customCommands:
  - key: 'N'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'feature branch'
            value: 'feature'
          - name: 'bugfix'
            description: 'bugfix branch'
            value: 'bugfx'
      - type: 'input'
        title: 'What is the JIRA ticket?'
        key: 'JiraTicket'
        initialValue: ''
      - type: 'input'
        title: 'Short descripion of the ticket'
        key: 'Description'
        initialValue: ''
    command: "git checkout -b {{.Form.BranchType}}/{{.Form.JiraTicket}}-{{.Form.Description}}"
    loadingText: 'Creating branch'
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  branchColors:
    'feature': '#74c7ec'
    'bugfix': '#f38ba8'
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"

