quitOnTopLevelReturn: true
customCommands:
  - key: 'N'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'feature branch'
            value: 'feature'
          - name: 'bugfix'
            description: 'bugfix branch'
            value: 'bugfix'
      - type: 'input'
        title: 'JIRA ticket'
        key: 'JiraTicket'
        initialValue: ''
      - type: 'input'
        title: 'Branch name (no spaces)'
        key: 'BranchName'
        initialValue: ''
    command: "git checkout -b {{.Form.BranchType}}/{{.Form.JiraTicket}}-{{.Form.BranchName}}"
    loadingText: 'Creating branch'
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  branchColors:
    'feature': '#74c7ec'
    'bugfix': '#f38ba8'
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
services:
  'github.rbx.com': 'github:github.rbx.com'

