vim.opt_local.spell = true
vim.opt_local.spelllang = "en_us"
vim.opt_local.linebreak = true
vim.opt_local.shiftwidth = 2
vim.opt_local.tabstop = 2
vim.opt_local.softtabstop = 2
vim.opt_local.textwidth = 100
vim.opt_local.breakindent = true
-- vim.opt_local.conceallevel = 0
